const lesson=(title,objective,paragraphs,example,activity,takeaway)=>({title,objective,paragraphs,example,activity,takeaway});
export const courses=[
{id:'organizacion',title:'Organiza tu negocio digital',category:'Organización',minutes:45,price:89,description:'Da orden a tus prioridades, tus tareas y la información de tu negocio.',audience:'Personas que gestionan un pequeño negocio y quieren trabajar con prioridades claras.',goals:['Definir un objetivo semanal comprobable.','Dividir el trabajo en tareas que puedas ejecutar.','Crear un sistema sencillo para solicitudes y archivos.'],resource:'planificacion-semanal.txt',lessons:[
lesson('Define un objetivo semanal.','Elegir un resultado concreto y realista para los próximos siete días.',[
'Una semana puede llenarse de mensajes, reuniones y tareas pequeñas sin que el negocio avance en lo que necesita. Un objetivo semanal sirve para decidir qué resultado merece atención. No es una lista de todo lo que quieres hacer: es una elección consciente. Empieza preguntándote qué cambio sería útil al terminar la semana y por qué ese cambio importa ahora.',
'Escribe el resultado con un verbo y una señal observable. “Mejorar la atención” puede interpretarse de muchas maneras. “Responder las cinco solicitudes pendientes antes del viernes” permite comprobar el avance. Evita depender por completo de decisiones ajenas: puedes preparar y enviar una propuesta clara, pero no garantizar que alguien la acepte. Formula el objetivo alrededor de aquello que puedes realizar.',
'Después, contrasta el resultado con el tiempo disponible. Revisa compromisos, tareas habituales y posibles interrupciones. Si solo tienes dos espacios de treinta minutos, reduce el alcance hasta que resulte razonable. Reservar margen no significa trabajar menos: permite terminar algo útil incluso cuando aparece un imprevisto. Anota también qué dejarás para otra semana para proteger esa decisión.',
'Por último, define cómo revisarás el objetivo. Puede ser una lista de solicitudes respondidas, un documento terminado o una carpeta organizada. Elige una evidencia sencilla y una fecha de revisión. Si cambian las condiciones, ajusta el objetivo de forma explícita. La intención es orientar el trabajo y aprender a estimar, no convertir la planificación en una obligación imposible.'
],'Una tienda recibe consultas por varios canales. Su objetivo será: “Registrar las ocho consultas pendientes en una sola lista y responderlas antes del viernes a las 16:00”.','Escribe un objetivo semanal. Incluye un resultado, una cantidad o evidencia y una fecha.','Un objetivo útil describe un resultado que puedes comprobar.'),
lesson('Convierte objetivos en tareas concretas.','Transformar un resultado deseado en acciones pequeñas y ejecutables.',[
'Un objetivo indica adónde quieres llegar; las tareas muestran qué harás para acercarte. Cuando una tarea dice “resolver el catálogo”, todavía es necesario decidir por dónde empezar. Esa decisión pendiente suele retrasar el trabajo. Divide el resultado en acciones que comiencen con un verbo concreto: reunir, redactar, revisar, ordenar o enviar. Cada acción debe producir algo reconocible.',
'Trabaja desde el resultado hacia atrás. Para enviar un catálogo necesitas revisarlo; para revisarlo necesitas una versión completa; para completarlo necesitas descripciones, precios e imágenes. Esta cadena revela dependencias. No necesitas un diagrama complejo: una lista numerada suele bastar. Distingue lo que puedes empezar hoy de lo que requiere una respuesta o un archivo que aún no tienes.',
'Calcula un tiempo aproximado para cada acción. Si una tarea parece ocupar toda la tarde, intenta dividirla en partes más fáciles de terminar. “Redactar las descripciones de tres productos” ofrece un punto de cierre más claro que “trabajar en contenido”. Incluye el tiempo para revisar y corregir, porque una primera versión rara vez está lista para compartirse.',
'Asigna una persona responsable cuando participen varias y establece un siguiente paso para las tareas bloqueadas. Trabaja con pocos estados: pendiente, en curso y terminado. Evita comenzar muchas cosas a la vez. Al cerrar una tarea, verifica su resultado antes de cambiar el estado. Una lista útil reduce decisiones durante el trabajo; si mantenerla exige más tiempo que ejecutar las acciones, simplifica el sistema.'
],'Para responder ocho consultas: reunir mensajes (10 min), identificar información faltante (10 min), preparar respuestas (20 min) y revisar y enviar (15 min).','Divide el objetivo anterior en tres tareas. Indica una duración estimada y cuál debes hacer primero.','Una tarea concreta deja claro qué hacer y cuándo está terminada.'),
lesson('Organiza solicitudes y archivos.','Crear un lugar de referencia para la información que utilizas cada día.',[
'Buscar un archivo entre conversaciones consume tiempo y favorece errores. La solución no requiere muchas aplicaciones: necesitas un lugar de referencia y una regla que puedas mantener. Empieza identificando qué información se repite en tu trabajo. Las solicitudes, los documentos de clientes y las propuestas suelen necesitar un orden distinto, aunque pueden conectarse mediante un nombre o código compartido.',
'Para las solicitudes, utiliza una tabla sencilla con fecha, asunto, responsable, estado y próximo paso. Registra solo lo necesario para actuar. Una fila debe permitir comprender qué falta sin volver a leer una conversación completa. Si una solicitud llega por otro canal, agrégala al registro cuando la revises. Evita tener dos listas principales que compitan por ser la versión actual.',
'Para los archivos, define carpetas por proyecto o tipo de trabajo y usa nombres que expliquen su contenido. Una convención como “2026-09_propuesta_tienda_v01” aporta fecha, asunto y versión. Elige una forma de nombrar y mantenla. Separa los borradores de los documentos listos para compartir para reducir el riesgo de enviar una versión anterior o un archivo incompleto.',
'Dedica unos minutos al cierre del día para registrar pendientes y colocar archivos nuevos. Un sistema sencillo pierde utilidad si solo se organiza una vez. Revisa también quién necesita acceder a cada carpeta y evita incluir información innecesaria. En esta actividad usa datos ficticios. El objetivo es practicar una estructura comprensible, no trasladar información real de clientes a una herramienta de demostración.'
],'La solicitud “Cambiar horario del folleto” queda como S-014, pendiente de confirmar el horario. Sus documentos viven en la carpeta S-014_folleto y la versión revisada termina en v02.','Propón cinco columnas para tu registro y escribe un nombre de archivo que incluya asunto y versión.','Un único lugar de referencia evita búsquedas y versiones confusas.'),
lesson('Revisa avances y pendientes.','Cerrar la semana con una revisión breve que permita decidir el siguiente paso.',[
'Una revisión semanal sirve para aprender de lo ocurrido y decidir qué sigue. No es una calificación de tu productividad. Reserva un momento breve y abre el objetivo que definiste al empezar. Compara la evidencia disponible con el resultado esperado: qué se terminó, qué quedó a medias y qué cambió. Describe hechos antes de buscar explicaciones o hacer nuevos planes.',
'Revisa las tareas pendientes una por una. Algunas siguen siendo importantes, otras necesitan información y otras ya no aportan valor. Evita trasladarlas automáticamente a la siguiente semana. Para cada una elige una acción: continuar, dividir, esperar una respuesta o descartar. Si depende de alguien, registra qué necesitas y cuándo conviene volver a consultar. Así la espera deja de ser un pendiente indefinido.',
'Observa tus estimaciones de tiempo. Si una tarea tomó el doble de lo previsto, identifica qué faltaba considerar: revisión, búsqueda de archivos, interrupciones o cambios de alcance. Usa esa observación para ajustar la siguiente planificación. No hace falta medir cada minuto; basta con reconocer patrones que ayuden a elegir compromisos más realistas y a reservar un margen adecuado.',
'Cierra la revisión con una decisión pequeña. Puede ser conservar una regla de nombres, preparar información antes de comenzar o limitar las tareas simultáneas. Escribe el próximo objetivo y la primera acción para iniciarlo. Una revisión útil termina con claridad, no con una lista cada vez más larga. El sistema debe acompañar el trabajo real y cambiar cuando encuentres una forma más simple de avanzar.'
],'Se respondieron seis de ocho consultas. Las otras dos requieren confirmar existencias. El siguiente paso es pedir esa información el lunes y reservar quince minutos para enviar las respuestas.','Anota un avance, un pendiente y una mejora para la próxima semana. Después responde la evaluación.','Revisar permite convertir lo ocurrido en mejores decisiones.')],quiz:[
{question:'¿Cuál es un objetivo semanal comprobable?',options:['Mejorar mucho el negocio.','Responder cinco solicitudes antes del viernes.','Estar ocupado toda la semana.'],correct:1,feedback:'La cantidad y la fecha permiten comprobar el resultado.'},
{question:'¿Qué tarea facilita comenzar?',options:['Arreglar todo el catálogo.','Pensar en el negocio.','Redactar las descripciones de tres productos.'],correct:2,feedback:'Una acción acotada tiene un punto de cierre claro.'},
{question:'¿Qué conviene hacer con un pendiente al revisar?',options:['Decidir si continuar, dividir, esperar o descartar.','Copiarlo siempre a la próxima semana.','Marcarlo como terminado para limpiar la lista.'],correct:0,feedback:'La revisión exige decidir qué sigue según la situación actual.'}]},
{id:'comunicacion',title:'Comunicación clara con clientes',category:'Comunicación',minutes:45,price:79,description:'Responde con claridad y convierte cada conversación en un siguiente paso.',audience:'Personas que atienden consultas, coordinan servicios o responden mensajes de clientes.',goals:['Identificar la información que falta en una solicitud.','Escribir mensajes fáciles de comprender.','Comunicar plazos y dar seguimiento con un propósito.'],resource:'guia-de-mensajes.txt',lessons:[
lesson('Comprende la solicitud antes de responder.','Identificar la necesidad de una persona y aclarar lo que falta.',[
'Responder rápido no siempre equivale a responder bien. Un mensaje como “necesito una página para mi negocio” contiene una intención, pero deja abiertas varias decisiones. Antes de proponer una solución, distingue lo que la persona ha dicho de lo que tú estás suponiendo. Esta separación evita ofrecer algo que parece adecuado y después resulta insuficiente o demasiado amplio.',
'Busca tres elementos: el resultado que necesita, el contexto en el que lo utilizará y las restricciones relevantes. Puedes preguntar qué espera que hagan sus visitantes, qué información ya tiene y si existe una fecha importante. No conviertas la conversación en un interrogatorio. Elige las preguntas que realmente cambian tu respuesta y agrúpalas en un mensaje breve y ordenado.',
'Resume lo que has entendido antes de avanzar. Una frase como “Entiendo que necesitas mostrar tus servicios y recibir consultas” permite que la otra persona corrija una interpretación equivocada. Si hay una ambigüedad importante, hazla visible. Evita dar por confirmado un plazo, una cantidad o un formato que todavía no se ha acordado. Aclarar temprano reduce cambios evitables.',
'Cierra el mensaje explicando qué harás con la información solicitada. Así las preguntas tienen un propósito visible. Puedes indicar que, cuando conozcas el alcance, prepararás una propuesta o confirmarás disponibilidad. Mantén un tono amable sin prometer resultados que aún no has evaluado. Escuchar y verificar no retrasa necesariamente el trabajo: crea una base más clara para la decisión siguiente y mejora la continuidad de la conversación.'
],'“Entiendo que quieres mostrar tus servicios. ¿Necesitas también reservas? ¿Ya tienes textos e imágenes? Con eso podré proponerte un alcance inicial”.','Redacta dos preguntas para aclarar esta solicitud: “Quiero mejorar la presentación de mi negocio”.','Primero verifica la necesidad; después propone una respuesta.'),
lesson('Escribe mensajes claros y completos.','Redactar una respuesta que la otra persona pueda entender y utilizar.',[
'Un mensaje claro permite reconocer rápidamente su propósito. Antes de escribir, decide qué necesita saber la otra persona y qué acción esperas después. Si intentas explicar demasiadas cosas al mismo tiempo, la información principal puede perderse. Empieza por la respuesta o la conclusión y añade el contexto necesario después. Usa palabras habituales y evita abreviaturas que solo tú conoces.',
'Organiza el contenido en tres partes: respuesta principal, información útil y siguiente paso. Si hay varias condiciones o entregables, utiliza una lista corta. Cada párrafo debe tratar una sola idea. Un mensaje completo no tiene que ser largo: contiene lo necesario para continuar sin obligar a la persona a adivinar cantidades, fechas, formatos o responsabilidades que afectan la decisión.',
'Revisa el tono al terminar. La brevedad puede sonar brusca si solo escribes órdenes, y un exceso de cortesía puede esconder la solicitud. Busca una combinación natural: saluda cuando corresponda, explica el punto y pide la acción de forma directa. Sustituye expresiones vagas como “a la brevedad” por una fecha concreta cuando tengas información suficiente para hacerlo.',
'Antes de enviar, comprueba nombres, archivos mencionados y coherencia entre el texto y lo que realmente ofreces. Si dices que adjuntas un documento, verifica que esté incluido. Lee el mensaje desde la perspectiva de alguien que no conoce tu proceso. Pregúntate si puede saber qué está confirmado, qué falta y qué debe hacer ahora. Esa lectura final suele detectar más problemas que añadir un párrafo adicional.'
],'“Podemos preparar un folleto de dos páginas. Incluye una propuesta visual y una ronda de ajustes. Para confirmar el inicio, envía los textos y las imágenes antes del martes”.','Reescribe “Sí, lo hacemos, pásame todo y vemos” como una respuesta con información útil y un siguiente paso.','Una respuesta clara dice qué ocurre y qué debe pasar después.'),
lesson('Comunica tiempos y próximos pasos.','Explicar un plazo con sus condiciones y avisar cuando cambie.',[
'Un plazo resulta útil cuando ambas partes entienden qué ocurrirá y desde cuándo se cuenta. “Lo tendrás pronto” puede significar cosas distintas para cada persona. Describe el entregable y una fecha o intervalo que puedas sostener. Cuando el inicio depende de recibir materiales o una confirmación, indica esa condición junto al plazo, no como una aclaración escondida al final.',
'Distingue una estimación de un compromiso confirmado. Si todavía necesitas revisar el alcance, dilo y explica cuándo podrás concretar la fecha. No inventes un plazo para cerrar la conversación. Una respuesta honesta permite planificar mejor que una promesa que después tendrás que corregir. Ten en cuenta también el tiempo de revisión de la otra persona si afecta a la entrega final.',
'Explica el próximo paso con una acción y un responsable. “Quedamos atentos” puede servir como cierre, pero no aclara quién debe hacer qué. Es más útil escribir “Tú nos envías los textos el martes; nosotros compartimos la primera versión el jueves”. Si intervienen varias personas, evita que todas crean que alguien más está resolviendo la tarea pendiente.',
'Cuando surja un cambio, comunícalo antes de que venza el plazo siempre que sea posible. Describe el hecho, su efecto y la alternativa disponible sin buscar culpables. Puedes proponer una entrega parcial o una nueva fecha, si son opciones reales. Actualiza lo acordado en un mensaje breve para que quede una referencia compartida. La claridad sobre los tiempos se mantiene durante todo el trabajo, no solo al aceptar la solicitud.'
],'“Si recibimos los textos completos el martes, compartiremos el primer borrador el jueves. Después necesitaremos tus comentarios para acordar la versión final”.','Escribe un plazo para un entregable e indica de qué depende y quién realiza el siguiente paso.','Un plazo claro incluye entregable, fecha y condiciones.'),
lesson('Realiza un seguimiento útil.','Retomar una conversación aportando contexto y una acción sencilla.',[
'Un seguimiento útil ayuda a continuar una conversación que quedó pendiente. Antes de escribir, revisa qué se acordó, quién tenía el siguiente paso y cuánto tiempo ha pasado. No todos los silencios requieren un recordatorio inmediato. Si ya existe una fecha de respuesta, respétala. Si no existe, elige un momento razonable según la importancia y el contexto de la solicitud.',
'Recupera el asunto con una referencia breve. La persona puede tener varias conversaciones abiertas y no recordar el detalle. Menciona la propuesta, el documento o la información pendiente sin copiar toda la historia. Añade una pregunta que permita responder con facilidad. “¿Quieres continuar con la opción de dos páginas?” es más concreta que “¿Alguna novedad?” cuando esa es la decisión que falta.',
'Aporta algo útil si corresponde: aclara una duda frecuente, recuerda una condición acordada o propone un siguiente paso. Evita crear urgencia artificial, insistir con mensajes idénticos o atribuir motivos al silencio. Un tono respetuoso reconoce que la otra persona puede necesitar más tiempo o haber cambiado de prioridad. Ofrece una salida clara, como retomar el tema más adelante.',
'Registra el resultado para no enviar recordatorios duplicados. Si llega una respuesta, actualiza el estado y la próxima acción. Si no llega después del seguimiento previsto, puedes cerrar el pendiente de forma temporal dejando una vía para retomarlo. La finalidad no es mantener todas las conversaciones activas para siempre, sino cuidar la continuidad y utilizar el tiempo de ambas partes con atención y claridad.'
],'“Hola, Alex. Retomo la propuesta del folleto enviada el lunes. ¿El alcance de dos páginas cubre lo que necesitas? Si prefieres revisarlo más adelante, podemos dejarlo pendiente”.','Escribe un seguimiento de hasta cuatro frases que aporte contexto, una pregunta concreta y una salida respetuosa.','Dar seguimiento es facilitar una decisión, no repetir un recordatorio.')],quiz:[
{question:'Una solicitud es ambigua. ¿Qué haces primero?',options:['Prometer el plazo más corto.','Aclarar el resultado esperado y la información que falta.','Enviar una propuesta genérica sin preguntas.'],correct:1,feedback:'Comprender el contexto permite proponer un alcance adecuado.'},
{question:'¿Qué plazo está mejor explicado?',options:['Lo antes posible.','En algún momento de la semana.','Primer borrador el jueves si recibimos los textos el martes.'],correct:2,feedback:'Esta frase define entregable, fecha y condición de inicio.'},
{question:'¿Qué caracteriza un seguimiento útil?',options:['Contexto y una pregunta concreta para avanzar.','Repetir “¿alguna novedad?” cada hora.','Inventar una fecha límite.'],correct:0,feedback:'El seguimiento debe facilitar la respuesta y respetar los acuerdos.'}]},
{id:'servicios',title:'Presenta tus servicios con claridad',category:'Negocios',minutes:60,price:99,description:'Explica qué ofreces, para quién y qué incluye tu trabajo, sin ambigüedades.',audience:'Profesionales independientes y pequeños negocios que necesitan explicar sus servicios.',goals:['Definir una audiencia y una necesidad concreta.','Delimitar entregables, condiciones y exclusiones.','Organizar una propuesta comprensible.'],resource:'plantilla-de-propuesta.txt',lessons:[
lesson('Define a quién ayudas.','Describir un grupo de personas con una necesidad compartida.',[
'Decir que tu servicio es “para todo el mundo” dificulta explicar por qué alguien debería prestarle atención. Definir a quién ayudas permite elegir ejemplos, palabras y entregables relevantes. No significa rechazar automáticamente a otras personas. Significa construir una presentación inicial que conecte con una situación concreta y que pueda adaptarse cuando conozcas mejor cada solicitud.',
'Empieza por el contexto de trabajo de tu audiencia. Piensa qué hace, qué intenta conseguir y qué dificultad aparece con frecuencia. Es más útil hablar de “profesionales que ofrecen varios servicios y reciben consultas confusas” que de una edad o una ubicación sin relación con la necesidad. El contexto explica por qué tu ayuda podría resultar valiosa en ese momento.',
'Distingue lo que sabes de lo que supones. Si todavía no has hablado con posibles clientes, escribe tu descripción como una hipótesis para revisar. Evita inventar comportamientos, presupuestos o preferencias. Puedes usar observaciones de tu experiencia, preguntas reales o ejemplos públicos, siempre sin convertir un caso aislado en una regla universal. Una audiencia bien definida se ajusta al aprender, no queda fijada para siempre.',
'Redacta una frase sencilla: “Ayudo a este tipo de persona a resolver esta situación mediante este servicio”. Comprueba que alguien externo pueda imaginar a quién te refieres. Si aparecen muchas audiencias con necesidades distintas, elige una para tu primera presentación. La claridad nace de tomar una decisión útil para comunicar, no de reunir todas las posibilidades en una sola frase demasiado amplia.'
],'“Ayudo a profesionales independientes con varios servicios a presentar su oferta en una página clara, para que sus visitantes sepan qué pueden consultar”.','Completa: “Ayudo a ___ que necesitan ___”. Usa una situación concreta, sin inventar datos de mercado.','Describe a tu audiencia por su contexto y su necesidad.'),
lesson('Explica el problema que resuelves.','Relacionar una dificultad reconocible con una mejora concreta.',[
'Una presentación de servicios suele empezar por herramientas o tareas: diseño, redacción, programación. Esa información puede ser necesaria, pero no explica por sí sola por qué el trabajo importa. Describe primero la dificultad que la persona reconoce. Puede ser información dispersa, consultas incompletas o una oferta difícil de comparar. Usa un lenguaje que permita identificar la situación sin exagerarla.',
'Conecta el problema con una consecuencia observable. Si los servicios están repartidos en varios mensajes, la persona interesada puede no encontrar qué incluye cada opción. No necesitas afirmar que el negocio pierde una cantidad de ventas que no has medido. Explica el efecto de forma prudente y concreta. La credibilidad depende más de la precisión que de presentar el problema como una emergencia.',
'Después describe el cambio que tu servicio puede producir directamente. Organizar una página de servicios puede facilitar la consulta de información; no garantiza que todas las visitas se conviertan en clientes. Separa el entregable, su utilidad y los resultados que dependen de otros factores. Así mantienes una propuesta atractiva sin prometer algo que no controlas ni puedes demostrar.',
'Prueba tu explicación con una frase de contraste temporal: antes la información estaba dispersa; después estará reunida y ordenada. Añade un ejemplo breve para hacer visible la mejora. Si necesitas muchos términos técnicos para explicar el valor, revisa la frase desde la perspectiva de la audiencia. El objetivo es que pueda reconocer su situación, entender el cambio propuesto y decidir si necesita conversar sobre ese servicio.'
],'“Cuando tus servicios están repartidos entre publicaciones, cuesta comparar qué incluye cada uno. Los organizamos en una página con alcance y formas de consulta”.','Escribe una dificultad, su efecto y una mejora que tu servicio pueda producir directamente.','Explica una mejora concreta sin prometer resultados que no controlas.'),
lesson('Describe entregables y alcance.','Delimitar qué recibirá la persona y qué condiciones acompañan el servicio.',[
'El alcance convierte una idea general en un acuerdo comprensible. “Diseño de presentación” puede significar cinco diapositivas para una persona y veinte para otra. Describe el entregable con cantidad, formato y características relevantes. El detalle no debe cubrir todas las posibilidades, pero sí las decisiones que cambian el esfuerzo, el precio o la utilidad del resultado final.',
'Aclara qué necesitas para comenzar. Puede ser un texto aprobado, imágenes con permiso de uso o información sobre el negocio. Indica quién aporta cada material y cómo afecta un retraso al calendario. Esta información permite evaluar si la persona está lista para iniciar el servicio. Evita asumir que redactar, buscar fotografías o traducir está incluido cuando solo se ha hablado de diseño.',
'Define cómo se revisará el trabajo. Una ronda de ajustes puede consistir en recibir comentarios agrupados sobre una versión. Explica ese significado y distingue una corrección de un cambio de alcance. Si la persona solicita más páginas o una nueva dirección, necesitarás revisar tiempo y condiciones antes de aceptar. Comunicarlo al principio evita convertir cada cambio en una sorpresa.',
'Incluye exclusiones relevantes con un tono sencillo. No hace falta una lista interminable de todo lo que no haces. Menciona aquello que podría confundirse con el servicio: impresión, mantenimiento o producción de contenido, por ejemplo. Finalmente, comprueba que entregables, condiciones y precio se refieren a la misma versión de la propuesta. Una descripción coherente protege la comprensión compartida y facilita decidir con información suficiente.'
],'“Incluye una presentación de ocho diapositivas en PDF y una ronda de ajustes. El cliente aporta textos e imágenes. No incluye redacción, impresión ni diapositivas adicionales”.','Define un entregable con cantidad y formato. Añade una condición de inicio y una exclusión relevante.','Un alcance claro explica qué incluye el trabajo y dónde termina.'),
lesson('Presenta una propuesta comprensible.','Reunir necesidad, alcance y siguiente paso en una propuesta breve.',[
'Una propuesta comprensible ayuda a decidir. Su estructura debe seguir las preguntas de quien la recibe: qué entendiste de su necesidad, qué propones, qué incluye, cuánto tiempo requiere y cómo puede continuar. No necesitas empezar con una larga historia del negocio. Resume el contexto y muestra la solución con suficiente detalle para que la persona compare lo ofrecido con lo que necesita.',
'Ordena el documento con títulos descriptivos y párrafos breves. Incluye el objetivo, los entregables, las condiciones de inicio, el calendario estimado y el precio correspondiente al alcance. En esta demostración utiliza importes ficticios. Si hay información pendiente, márcala como pendiente en lugar de rellenarla con una suposición. Una propuesta puede ser preliminar, pero debe decirlo con claridad.',
'Comprueba la consistencia entre las secciones. Si el alcance indica ocho diapositivas, el resumen y el calendario deben referirse al mismo trabajo. Explica cuándo comienza a contarse el plazo y qué ocurre después de la primera versión. Evita incorporar condiciones importantes únicamente en una nota difícil de encontrar. La lectura debe permitir reconocer los compromisos sin una explicación adicional por teléfono.',
'Termina con un siguiente paso sencillo: confirmar el alcance, responder una duda o entregar un material necesario. Antes de compartir, relee la propuesta desde la perspectiva del destinatario y elimina repeticiones. Verifica que los archivos mencionados existan y que no queden nombres de otro proyecto. Una buena presentación no busca parecer compleja; organiza decisiones y permite empezar la conversación con expectativas compartidas y revisables.'
],'“Proponemos una presentación de ocho diapositivas para explicar tus servicios. Incluye PDF y una ronda de ajustes. El plazo se confirma al recibir los textos. Siguiente paso: revisar y confirmar el alcance”.','Redacta una propuesta breve con necesidad, entregables, condiciones, plazo e importe ficticio. Termina con un siguiente paso.','La propuesta reúne la información necesaria para tomar una decisión.')],quiz:[
{question:'¿Qué descripción de audiencia es más útil?',options:['Todas las personas del mundo.','Cualquiera con dinero.','Profesionales que necesitan ordenar la información de sus servicios.'],correct:2,feedback:'El contexto y la necesidad permiten adaptar la propuesta.'},
{question:'¿Cuál es un entregable bien delimitado?',options:['Una presentación excelente.','Ocho diapositivas en PDF y una ronda de ajustes.','Todo lo que haga falta.'],correct:1,feedback:'Cantidad, formato y revisión ayudan a comprender el alcance.'},
{question:'¿Cómo debería cerrar una propuesta?',options:['Con una acción concreta para continuar.','Con una promesa de ventas garantizadas.','Sin indicar qué debe hacer el destinatario.'],correct:0,feedback:'Un siguiente paso claro facilita decidir y continuar.'}]}];
export const getCourse=id=>courses.find(c=>c.id===id);
